version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    command: ["redis-server", "--requirepass", "SecurePassword123"]
    volumes:
      - redis-data:/data
    networks:
      - mastra-network

  postgres:
    image: ankane/pgvector:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vector
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mastra-network

  mastra-app:
    build: .
    ports:
      - "4111:4111" # Change if your app uses a different port
      - "5000:5000"
    environment:
      MASTRA_TELEMETRY_DISABLED: "true"
      POSTHOG_DISABLED: "true"
      POSTGRES_VECTOR_CONNECTION_STRING: postgres://postgres:postgres@postgres:5432/vector
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
    networks:
      - mastra-network

volumes:
  redis-data:
  postgres-data:

networks:
  mastra-network:
    driver: bridge