services:
  mastra-app:
    build: .
    ports:
      - "4111:4111" # Change if your app uses a different port
      - "5000:5000"
    environment:
      MASTRA_TELEMETRY_DISABLED: "true"
      POSTHOG_DISABLED: "true"
    restart: unless-stopped
